source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, "8.0"

def pod_libraries 
  pod 'Moya-Argo', :path => "../"
  pod 'Moya-Argo/ReactiveSwift', :path => "../"
  pod 'Moya-Argo/RxSwift', :path => "../"
  pod "Curry"
end

target 'Moya-Argo_Example' do
  pod_libraries
end

target 'Moya-Argo_Tests' do
  pod_libraries
end
